import { notFound } from "next/navigation";
import { desc, eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { employees, leaveRecords } from "@/lib/db/schema";
import { archiveEmployee, deleteLeave, saveLeave, updateEmployee } from "@/app/actions";
import { EmployeeForm } from "@/components/employee-form";
import { LeaveModal } from "@/components/leave-modal";
import { ConfirmAction } from "@/components/confirm-action";
import { formatDate, formatMoney } from "@/lib/format";
import { getMessages } from "@/lib/locale";
export default async function EmployeePage({params}:{params:Promise<{employeeId:string}>}){const [{employeeId},{locale,messages}]=await Promise.all([params,getMessages()]);const [employee]=await db.select().from(employees).where(eq(employees.id,employeeId)).limit(1);if(!employee)notFound();const leaves=await db.select().from(leaveRecords).where(eq(leaveRecords.employeeId,employeeId)).orderBy(desc(leaveRecords.startDate));return <div className="page page-narrow"><div className="page-header"><div><h1 className="page-title">{employee.name}</h1><p className="page-description">{employee.role} · {employee.status=== "ACTIVE"?messages.common.active:messages.common.archived}</p></div>{employee.status==="ACTIVE"?<ConfirmAction action={archiveEmployee.bind(null,employeeId)} label={messages.employees.archive} confirmText="Archive this employee? Historical payroll will be preserved." danger/>:null}</div><EmployeeForm action={updateEmployee.bind(null,employeeId)} employee={employee} messages={messages}/><section className="profile-section"><div className="section-heading"><h2 className="section-title">{messages.employees.leaveHistory}</h2><LeaveModal employeeName={employee.name} action={saveLeave.bind(null,employeeId,null)} copy={messages.leave} triggerLabel={messages.employees.addLeave}/></div>{leaves.length?<div className="leave-list">{leaves.map(leave=><div className="leave-row" key={leave.id}><div><strong>{formatDate(leave.startDate,locale)}{leave.endDate!==leave.startDate?` – ${formatDate(leave.endDate,locale)}`:""}</strong><span>{leave.reason}</span></div><div className="leave-amount">{leave.hasSalaryDeduction?`−${formatMoney(leave.deductionAmount,locale)}`:messages.leave.none}</div><div className="row-actions"><LeaveModal employeeName={employee.name} leave={leave} action={saveLeave.bind(null,employeeId,leave.id)} copy={messages.leave} triggerLabel={messages.common.edit}/><ConfirmAction action={deleteLeave.bind(null,employeeId,leave.id)} label={messages.common.delete} confirmText="Delete this leave record? Draft payroll will be recalculated." danger/></div></div>)}</div>:<p className="empty-line">{messages.leave.noLeave}</p>}</section></div>}
