import { asc, eq } from "drizzle-orm";
import { ShieldPlus } from "lucide-react";
import { addApprovedAdmin, setAdminStatus } from "@/app/actions";
import { ConfirmAction } from "@/components/confirm-action";
import { requireSystemAdmin } from "@/lib/authorization";
import { db } from "@/lib/db";
import { approvedAdmins, user } from "@/lib/db/schema";
import { getMessages } from "@/lib/locale";
export const metadata={title:"Administrators"};
export default async function AdminsPage(){await requireSystemAdmin();const {messages}=await getMessages("admins", "employees", "common");const admins=await db.select({approval:approvedAdmins,name:user.name}).from(approvedAdmins).leftJoin(user,eq(approvedAdmins.email,user.email)).orderBy(asc(approvedAdmins.email));return <div className="page"><div className="page-header"><div><h1 className="page-title">{messages.admins.title}</h1><p className="page-description">{messages.admins.help}</p></div></div><form action={addApprovedAdmin} className="admin-add"><div><label className="label" htmlFor="adminEmail">{messages.admins.email}</label><input className="input" id="adminEmail" name="email" type="email" required placeholder="hr@example.com"/></div><button className="button button-primary"><ShieldPlus size={17}/>{messages.admins.add}</button></form><div className="table-wrap"><table className="data-table"><thead><tr><th>{messages.admins.email}</th><th>{messages.employees.name}</th><th>{messages.admins.role}</th><th>{messages.admins.status}</th><th></th></tr></thead><tbody>{admins.map(({approval,name})=><tr key={approval.id}><td className="employee-name">{approval.email}</td><td>{name??"—"}</td><td>{approval.role==="SYSTEM_ADMIN"?messages.admins.system:messages.admins.hr}</td><td><span className={`status ${approval.status==="ACTIVE"?"status-active":""}`}>{approval.status==="ACTIVE"?messages.common.active:"Revoked"}</span></td><td className="money">{approval.role==="HR_ADMIN"?<ConfirmAction action={setAdminStatus.bind(null,approval.id,approval.status==="ACTIVE"?"REVOKED":"ACTIVE")} label={approval.status==="ACTIVE"?messages.admins.revoke:messages.admins.reactivate} confirmText={approval.status==="ACTIVE"?"Revoke this administrator's access and sessions?":"Reactivate this administrator?"} danger={approval.status==="ACTIVE"}/>:null}</td></tr>)}</tbody></table></div></div>}
