import Link from "next/link";
import { CalendarRange } from "lucide-react";
import { desc, eq, sql } from "drizzle-orm";
import { db } from "@/lib/db";
import { payrollPeriods, payrollRecords } from "@/lib/db/schema";
import { generatePayroll } from "@/app/actions";
import { formatMoney, monthLabel } from "@/lib/format";
import { getMessages } from "@/lib/locale";
export const metadata={title:"Payroll"};
export default async function PayrollPage(){const {locale,messages}=await getMessages("payroll", "employees", "common");const periods=await db.select({period:payrollPeriods,total:sql<string>`coalesce(sum(${payrollRecords.netSalary}),0)`,employees:sql<number>`count(${payrollRecords.id})::int`}).from(payrollPeriods).leftJoin(payrollRecords,eq(payrollPeriods.id,payrollRecords.payrollPeriodId)).groupBy(payrollPeriods.id).orderBy(desc(payrollPeriods.payrollMonth));const current=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Bangkok",year:"numeric",month:"2-digit"}).format(new Date()).slice(0,7);return <div className="page"><div className="page-header"><div><h1 className="page-title">{messages.payroll.title}</h1><p className="page-description">{messages.payroll.history}</p></div></div><form action={generatePayroll} className="payroll-generate"><div><label className="label" htmlFor="month">{messages.payroll.month}</label><input className="input" id="month" name="month" type="month" defaultValue={current} required/></div><button className="button button-primary"><CalendarRange size={17}/>{messages.payroll.generate}</button></form><section className="payroll-history"><h2 className="section-title">{messages.payroll.history}</h2>{periods.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>{messages.payroll.month}</th><th>{messages.employees.title}</th><th>{messages.employees.status}</th><th className="money">{messages.payroll.total}</th></tr></thead><tbody>{periods.map(({period,total,employees:count})=><tr key={period.id}><td><Link className="employee-name" href={`/payroll/${period.payrollMonth.slice(0,7)}`}>{monthLabel(period.payrollMonth,locale)}</Link></td><td>{count}</td><td><span className={`status status-${period.status.toLowerCase()}`}>{period.status==="DRAFT"?messages.common.draft:messages.common.finalized}</span></td><td className="money">{formatMoney(total,locale)}</td></tr>)}</tbody></table></div>:<div className="empty-state"><h2>{messages.payroll.noPeriods}</h2><p>{messages.payroll.noPeriodsHelp}</p></div>}</section></div>}
