import Link from "next/link";
import { PhotoInput } from "@/components/photo-input";
import type { WorkSchedule } from "@/lib/db/schema";

const days = ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"] as const;
export const defaultSchedule = Object.fromEntries(days.map((day, index) => [day, index < 5 ? { working: true, start: "09:00", end: "18:00" } : { working: false }])) as WorkSchedule;
export function EmployeeForm({ action, employee, messages }: { action: (formData: FormData) => void | Promise<void>; employee?: { name:string; role:string; monthlySalary:string|null; photoUrl:string|null; workSchedule:WorkSchedule }; messages: { employees: Record<string,string>; common: Record<string,string> } }) {
  const schedule = employee?.workSchedule ?? defaultSchedule;
  return <form action={action}><section className="form-section"><h2 className="section-title">{messages.employees.basicInfo}</h2><div className="form-stack"><PhotoInput currentUrl={employee?.photoUrl} labels={{photo:messages.employees.photo,upload:messages.employees.upload,camera:messages.employees.camera,capture:messages.employees.capture,cameraLoading:messages.employees.cameraLoading,cameraError:messages.employees.cameraError,previewAlt:messages.employees.previewAlt,editPhoto:messages.employees.editPhoto,cropHelp:messages.employees.cropHelp,zoom:messages.employees.zoom,horizontalPosition:messages.employees.horizontalPosition,verticalPosition:messages.employees.verticalPosition,rotate:messages.employees.rotate,flipHorizontal:messages.employees.flipHorizontal,flipVertical:messages.employees.flipVertical,resetPhoto:messages.employees.resetPhoto,usePhoto:messages.employees.usePhoto,retake:messages.employees.retake,photoError:messages.employees.photoError,photoLoading:messages.employees.photoLoading,photoSaving:messages.employees.photoSaving,cancel:messages.common.cancel}}/><div className="field-grid"><div><label className="label" htmlFor="name">{messages.employees.name}</label><input id="name" name="name" className="input" defaultValue={employee?.name} required /></div><div><label className="label" htmlFor="role">{messages.employees.role}</label><input id="role" name="role" className="input" defaultValue={employee?.role} required /></div></div><div className="salary-field"><label className="label" htmlFor="salary">{messages.employees.salary}</label><div className="salary-input"><span>฿</span><input id="salary" name="monthlySalary" className="input" inputMode="decimal" pattern="\d+(\.\d{1,2})?" defaultValue={employee?.monthlySalary ?? ""} /></div><div className="field-help">{messages.common.notSet} — {messages.common.optional}</div></div></div></section><section className="form-section"><h2 className="section-title">{messages.employees.schedule}</h2><div className="schedule-list">{days.map((day) => <div className="schedule-row" key={day}><label className="schedule-day"><input type="checkbox" name={`${day}.working`} defaultChecked={schedule[day].working}/><span>{messages.employees[day]}</span></label><div className="schedule-time"><input className="input" type="time" name={`${day}.start`} defaultValue={schedule[day].start ?? "09:00"}/><span>–</span><input className="input" type="time" name={`${day}.end`} defaultValue={schedule[day].end ?? "18:00"}/></div></div>)}</div></section><div className="form-actions"><Link href="/employees" className="button button-secondary">{messages.common.cancel}</Link><button className="button button-primary" type="submit">{messages.common.save}</button></div></form>;
}
