"use client";
import { useState } from "react";
import { CalendarPlus, X } from "lucide-react";

type Leave = { id:string; startDate:string; endDate:string; reason:string; hasSalaryDeduction:boolean; deductionAmount:string; deductionPayrollMonth:string };
export function LeaveModal({ employeeName, action, copy, leave, triggerLabel }: { employeeName:string; action:(formData:FormData)=>void|Promise<void>; copy:Record<string,string>; leave?:Leave; triggerLabel:string }) {
  const currentMonth=new Date().toISOString().slice(0,7);
  const [open,setOpen]=useState(false);
  const [deduct,setDeduct]=useState(leave?.hasSalaryDeduction ?? false);
  const [payrollMonth,setPayrollMonth]=useState(leave?.deductionPayrollMonth.slice(0,7) ?? currentMonth);
  return <><button type="button" className={leave ? "button button-ghost button-small" : "button button-secondary"} onClick={()=>setOpen(true)}>{leave ? null : <CalendarPlus size={16}/>} {triggerLabel}</button>{open ? <div className="dialog-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget)setOpen(false)}}><div className="dialog" role="dialog" aria-modal="true"><form action={action}><div className="dialog-header"><div><h2 className="section-title">{triggerLabel}</h2><span className="subtle">{employeeName}</span></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="dialog-body form-stack"><div className="field-grid"><div><label className="label">{copy.start}</label><input className="input" name="startDate" type="date" defaultValue={leave?.startDate} onChange={(event)=>{if(!leave&&event.target.value)setPayrollMonth(event.target.value.slice(0,7))}} required/></div><div><label className="label">{copy.end}</label><input className="input" name="endDate" type="date" defaultValue={leave?.endDate} required/></div></div><div><label className="label">{copy.reason}</label><textarea className="input" name="reason" defaultValue={leave?.reason} required/></div><label className="check-row"><input type="checkbox" name="hasSalaryDeduction" checked={deduct} onChange={(event)=>setDeduct(event.target.checked)}/><span>{copy.deduction}</span></label>{deduct ? <div className="field-grid"><div><label className="label">{copy.amount}</label><div className="salary-input"><span>฿</span><input className="input" name="deductionAmount" inputMode="decimal" defaultValue={leave?.deductionAmount} required/></div></div><div><label className="label">{copy.month}</label><input className="input" name="deductionPayrollMonth" type="month" value={payrollMonth} onChange={(event)=>setPayrollMonth(event.target.value)} required/></div></div> : <input type="hidden" name="deductionPayrollMonth" value={payrollMonth}/>}</div><div className="dialog-actions"><button type="button" className="button button-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button button-primary">{copy.save}</button></div></form></div></div> : null}</>;
}
