/* eslint-disable @next/next/no-img-element -- previews include temporary camera blob URLs */
"use client";
import { Camera, Upload, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";

export function PhotoInput({ currentUrl, labels }: { currentUrl?: string | null; labels: { photo: string; upload: string; camera: string } }) {
  const [preview, setPreview] = useState(currentUrl ?? ""); const [cameraOpen, setCameraOpen] = useState(false); const [error, setError] = useState("");
  const video = useRef<HTMLVideoElement>(null); const canvas = useRef<HTMLCanvasElement>(null); const fileInput = useRef<HTMLInputElement>(null); const stream = useRef<MediaStream | null>(null);
  useEffect(() => () => stream.current?.getTracks().forEach((track) => track.stop()), []);
  async function openCamera() { try { setError(""); stream.current = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "user" }, audio: false }); setCameraOpen(true); setTimeout(() => { if (video.current && stream.current) { video.current.srcObject = stream.current; void video.current.play(); } }, 0); } catch { setError("Camera access is unavailable. You can upload a photo instead."); } }
  function closeCamera() { stream.current?.getTracks().forEach((track) => track.stop()); stream.current = null; setCameraOpen(false); }
  function capture() { if (!video.current || !canvas.current || !fileInput.current) return; const context = canvas.current.getContext("2d"); if (!context) return; canvas.current.width = video.current.videoWidth; canvas.current.height = video.current.videoHeight; context.drawImage(video.current, 0, 0); canvas.current.toBlob((blob) => { if (!blob || !fileInput.current) return; const file = new File([blob], "camera-photo.jpg", { type: "image/jpeg" }); const transfer = new DataTransfer(); transfer.items.add(file); fileInput.current.files = transfer.files; setPreview(URL.createObjectURL(file)); closeCamera(); }, "image/jpeg", .88); }
  return <div className="photo-input"><div className="photo-preview">{preview ? <img src={preview} alt="Employee preview" /> : <Camera size={26} />}</div><div><span className="label">{labels.photo}</span><div className="photo-actions"><label className="button button-secondary button-small"><Upload size={15}/>{labels.upload}<input ref={fileInput} name="photo" type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={(e) => { const file=e.target.files?.[0]; if(file) setPreview(URL.createObjectURL(file)); }} /></label><button type="button" className="button button-secondary button-small" onClick={openCamera}><Camera size={15}/>{labels.camera}</button></div>{error ? <div className="field-error">{error}</div> : null}</div><canvas ref={canvas} hidden />{cameraOpen ? <div className="dialog-backdrop"><div className="dialog camera-dialog"><div className="dialog-header"><h2 className="section-title">{labels.camera}</h2><button type="button" className="icon-button" onClick={closeCamera}><X size={18}/></button></div><video ref={video} muted playsInline /><div className="dialog-actions"><button type="button" className="button button-secondary" onClick={closeCamera}>Cancel</button><button type="button" className="button button-primary" onClick={capture}><Camera size={16}/>Capture</button></div></div></div> : null}</div>;
}
