/* eslint-disable @next/next/no-img-element -- photo URLs are storage-provider supplied at runtime */
import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";
import { AlertTriangle, CheckCircle2, RefreshCw } from "lucide-react";
import { db } from "@/lib/db";
import { employees, payrollPeriods, payrollRecords } from "@/lib/db/schema";
import { finalizePayroll, recalculatePayroll, reopenPayroll } from "@/app/actions";
import { ConfirmAction } from "@/components/confirm-action";
import { formatMoney, monthLabel, normalizeMonth } from "@/lib/format";
import { getMessages } from "@/lib/locale";
export default async function PayrollMonthPage({params}:{params:Promise<{month:string}>}){const [{month},{locale,messages}]=await Promise.all([params,getMessages()]);const [period]=await db.select().from(payrollPeriods).where(eq(payrollPeriods.payrollMonth,normalizeMonth(month))).limit(1);if(!period)notFound();const records=await db.select({record:payrollRecords,employee:employees}).from(payrollRecords).innerJoin(employees,eq(payrollRecords.employeeId,employees.id)).where(eq(payrollRecords.payrollPeriodId,period.id)).orderBy(employees.name);const total=records.reduce((sum,{record})=>sum+Number(record.netSalary??0),0);return <div className="page"><div className="page-header"><div><h1 className="page-title">{monthLabel(month,locale)}</h1><p className="page-description"><span className={`status status-${period.status.toLowerCase()}`}>{period.status==="DRAFT"?messages.common.draft:messages.common.finalized}</span></p></div><div className="header-actions">{period.status==="DRAFT"?<><form action={recalculatePayroll.bind(null,month)}><button className="button button-secondary"><RefreshCw size={16}/>{messages.payroll.recalculate}</button></form><ConfirmAction action={finalizePayroll.bind(null,period.id,month)} label={messages.payroll.finalize} confirmText="Finalize this payroll? Values will be preserved as historical snapshots."/></>:<ConfirmAction action={reopenPayroll.bind(null,period.id,month)} label={messages.payroll.reopen} confirmText="Reopen and recalculate this payroll using current salary and leave data?"/>}</div></div><div className="payroll-total"><span>{messages.payroll.total}</span><strong>{formatMoney(total,locale)}</strong></div><div className="table-wrap"><table className="data-table"><thead><tr><th>{messages.payroll.employee}</th><th className="money">{messages.payroll.base}</th><th className="money">{messages.payroll.deduction}</th><th className="money">{messages.payroll.net}</th></tr></thead><tbody>{records.map(({record,employee})=><tr key={record.id}><td><div className="employee-cell"><span className="avatar">{employee.photoUrl?<img src={employee.photoUrl} alt=""/>:employee.name.slice(0,2).toUpperCase()}</span><div><span className="employee-name">{employee.name}</span>{record.deductionExceedsSalary?<span className="payroll-warning"><AlertTriangle size={13}/>Deductions exceeded salary</span>:null}</div></div></td><td className="money">{record.baseSalarySnapshot?formatMoney(record.baseSalarySnapshot,locale):messages.payroll.missingSalary}</td><td className="money">{record.baseSalarySnapshot?`−${formatMoney(record.leaveDeductionTotal,locale)}`:"—"}</td><td className="money payroll-net">{record.netSalary?formatMoney(record.netSalary,locale):<span className="cannot-calculate">{messages.payroll.cannotCalculate}</span>}</td></tr>)}</tbody></table></div>{period.status==="FINALIZED"?<p className="finalized-note"><CheckCircle2 size={16}/>Historical values are locked until this payroll is reverted to draft.</p>:null}</div>}
