/* eslint-disable @next/next/no-img-element -- photo URLs are storage-provider supplied at runtime */
import Link from "next/link";
import { Search, UserPlus } from "lucide-react";
import { asc, ilike, or } from "drizzle-orm";
import { db } from "@/lib/db";
import { employees } from "@/lib/db/schema";
import { getMessages } from "@/lib/locale";
import { formatMoney } from "@/lib/format";
export const metadata={title:"Employees"};
export default async function EmployeesPage({searchParams}:{searchParams:Promise<{q?:string}>}) { const [{q=""},{locale,messages}]=await Promise.all([searchParams,getMessages()]); const list=await db.select().from(employees).where(q?or(ilike(employees.name,`%${q}%`),ilike(employees.role,`%${q}%`)):undefined).orderBy(asc(employees.name)); return <div className="page"><div className="page-header"><div><h1 className="page-title">{messages.employees.title}</h1><p className="page-description">{list.length} {messages.employees.title.toLowerCase()}</p></div><Link href="/employees/new" className="button button-primary"><UserPlus size={17}/>{messages.employees.add}</Link></div><form className="search-form"><Search size={17}/><input name="q" defaultValue={q} placeholder={messages.employees.searchPlaceholder}/><button className="button button-secondary button-small">{messages.common.search}</button></form>{list.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>{messages.employees.name}</th><th>{messages.employees.role}</th><th className="money">{messages.employees.salary}</th><th>{messages.employees.status}</th><th><span className="sr-only">{messages.common.actions}</span></th></tr></thead><tbody>{list.map(e=><tr key={e.id}><td><div className="employee-cell"><span className="avatar">{e.photoUrl?<img src={e.photoUrl} alt=""/>:e.name.slice(0,2).toUpperCase()}</span><Link className="employee-name" href={`/employees/${e.id}`}>{e.name}</Link></div></td><td>{e.role}</td><td className="money">{formatMoney(e.monthlySalary,locale)??messages.common.notSet}</td><td><span className={`status ${e.status==="ACTIVE"?"status-active":""}`}>{e.status==="ACTIVE"?messages.common.active:messages.common.archived}</span></td><td className="money"><Link href={`/employees/${e.id}`} className="button button-ghost button-small">View</Link></td></tr>)}</tbody></table></div>:<div className="empty-state"><h2>{messages.employees.noEmployees}</h2><p>{messages.employees.noEmployeesHelp}</p><Link href="/employees/new" className="button button-primary">{messages.employees.add}</Link></div>}</div>; }
